services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    ports:
      - "3030:8080"
    environment:
      OPENAI_API_URL: "http://pipelines:9099"

    volumes:
      - ./open-webui:/app/backend/data 
    depends_on:
      - pipelines
    networks:
      - webui-net
  pipelines:
      build:
        context: .
        dockerfile: Dockerfile.pipelines
      image: openwebui/pipelines-node:latest   
      ports:
        - "9099:9099"
      volumes:
        - ./pipelines:/app/pipelines
        - ./open-webui/uploads:/app/uploads
        - ./open-webui/webui.db:/app/webui.db
        - ./pptx_folder:/app/pptx_folder
        - ./templates:/app/templates
        - ./OUTPUT:/app/OUTPUT
        - ./mappings:/app/mappings
        - ./src:/app/src
        - ./.env:/app/.env
      environment:
        - PIPELINES_REQUIREMENTS_PATH=/app/pipelines/requirements.txt
        - MAPPINGS_FOLDER=/app/mappings
      networks:
        - webui-net
        
  fastapi:
    profiles:
      - api
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: fastapi_app
    ports:
      - "5050:5050"
    volumes:
      - .:/app  
    depends_on:
      - pipelines
    networks:
      - webui-net

networks:
  webui-net:
